export const incidents = [
  {
    id: 'knight',
    title: 'Knight Capital',
    year: 2012,
    loss: '$440M',
    lossValue: 440,
    duration: '45 minutes',
    category: 'software',
    tag: 'Software',
    short: 'A single unused flag on one server turned a routine deployment into a $440 million catastrophe in under an hour.',
    story: [
      'On August 1, 2012, Knight Capital Group deployed new code for a NYSE Retail Liquidity Program.',
      'Seven of eight servers received the correct update. One server retained an old binary that still contained a dormant “Power Peg” feature flag.',
      'When the market opened, that flag caused the system to send millions of orders at high speed with almost no risk controls.',
      'In 45 minutes the firm accumulated a $440 million loss. Its capital base was effectively destroyed. Days later it was acquired.',
    ],
    lessons: [
      'Every automated trading system needs an instantaneous kill switch.',
      'Feature flags must have strict lifecycle management and deployment validation.',
      'Never deploy to 100% of capacity at once — use canaries.',
      'Dead code paths that can be re-activated by configuration are time bombs.',
    ],
    references: [
      { label: 'SEC Order', url: 'https://www.sec.gov/litigation/admin/2013/34-70694.pdf' },
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Knight_Capital_Group' },
    ],
  },
  {
    id: 'wirecard',
    title: 'Wirecard',
    year: 2020,
    loss: '€1.9B',
    lossValue: 1900,
    duration: 'Years of fraud',
    category: 'fraud',
    tag: 'Governance',
    short: 'A high-flying German fintech collapsed after €1.9 billion in cash simply did not exist.',
    story: [
      'Wirecard presented itself as a global payments success story and a DAX member.',
      'For years, auditors and regulators failed to verify the existence of large cash balances held at Asian trustee accounts.',
      'In June 2020 the company admitted that €1.9 billion was missing. The stock collapsed. Insolvency followed within days.',
      'The scandal exposed deep failures in audit quality, regulatory oversight, and corporate governance.',
    ],
    lessons: [
      'Independent verification of cash and third-party balances is non-negotiable.',
      'High growth and complex international structures demand heightened scrutiny.',
      'Regulators must have the tools and will to challenge successful companies.',
    ],
    references: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Wirecard_scandal' },
    ],
  },
  {
    id: 'svb',
    title: 'Silicon Valley Bank',
    year: 2023,
    loss: '$209B',
    lossValue: 209000,
    duration: '48 hours',
    category: 'liquidity',
    tag: 'Liquidity',
    short: 'The second-largest bank failure in U.S. history began with interest-rate risk and ended in a classic bank run.',
    story: [
      'SVB held a large portfolio of long-duration securities purchased when rates were near zero.',
      'Rising rates created massive unrealized losses. When depositors began withdrawing, the bank was forced to sell at a loss.',
      'A failed capital raise and social-media-amplified panic triggered a historic digital bank run.',
      'Regulators closed the bank on March 10, 2023. The episode reshaped how the industry thinks about interest-rate risk and uninsured deposits.',
    ],
    lessons: [
      'Interest-rate risk must be actively managed even in “safe” government securities.',
      'Concentration of uninsured deposits creates extreme run risk in the digital age.',
      'Communication and capital planning under stress are as important as the balance sheet.',
    ],
    references: [
      { label: 'FDIC', url: 'https://www.fdic.gov/' },
    ],
  },
  {
    id: 'bangladesh',
    title: 'Bangladesh Bank Heist',
    year: 2016,
    loss: '$81M',
    lossValue: 81,
    duration: 'Hours',
    category: 'cyber',
    tag: 'Cyber',
    short: 'Hackers used stolen SWIFT credentials to attempt to steal nearly $1 billion from Bangladesh’s central bank.',
    story: [
      'In February 2016 attackers gained access to Bangladesh Bank’s SWIFT terminals.',
      'They issued dozens of fraudulent payment instructions totaling nearly $1 billion.',
      'Most were blocked, but $81 million was successfully transferred and largely disappeared into the Philippine casino system.',
      'The attack highlighted the critical importance of endpoint security around high-value payment systems.',
    ],
    lessons: [
      'SWIFT access must be protected with multi-layered controls and monitoring.',
      'Out-of-band verification for large-value transfers is essential.',
      'Central banks are high-value targets and must treat security accordingly.',
    ],
    references: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Bangladesh_Bank_robbery' },
    ],
  },
  {
    id: 'ftx',
    title: 'FTX',
    year: 2022,
    loss: '$8B+',
    lossValue: 8000,
    duration: 'Days',
    category: 'fraud',
    tag: 'Governance',
    short: 'One of the largest crypto exchanges collapsed after customer funds were allegedly used to cover related-party losses.',
    story: [
      'FTX and Alameda Research operated with extreme intermingling of customer and proprietary funds.',
      'When a liquidity crisis hit, the exchange could not meet withdrawal demands.',
      'Bankruptcy filings revealed an $8+ billion hole and a near-total absence of corporate controls.',
      'The collapse accelerated regulatory focus on crypto custody, segregation of assets, and exchange governance.',
    ],
    lessons: [
      'Customer assets must be fully segregated and independently verifiable.',
      'Related-party exposure and leverage must be transparent and limited.',
      '“Move fast” culture is incompatible with custody of customer funds.',
    ],
    references: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Bankruptcy_of_FTX' },
    ],
  },
  {
    id: 'madoff',
    title: 'Bernie Madoff',
    year: 2008,
    loss: '$65B',
    lossValue: 65000,
    duration: 'Decades',
    category: 'fraud',
    tag: 'Fraud',
    short: 'The largest known Ponzi scheme in history destroyed $65 billion in paper wealth and shattered trust in investment management.',
    story: [
      'Bernard Madoff ran a decades-long Ponzi scheme under the guise of a sophisticated investment advisory business.',
      'Consistent, impossible returns were manufactured by using new investor money to pay earlier investors.',
      'The 2008 financial crisis triggered redemption requests the scheme could not meet. The fraud was exposed in December 2008.',
      'The case led to major reforms in custody rules, auditor independence, and whistleblower protections.',
    ],
    lessons: [
      'Independent custody and third-party verification are fundamental.',
      'Returns that appear too consistent for the strategy should trigger deep due diligence.',
      'Regulators need resources and incentives to investigate persistent red flags.',
    ],
    references: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Madoff_investment_scandal' },
    ],
  },
  {
    id: 'coincheck',
    title: 'Coincheck',
    year: 2018,
    loss: '$530M',
    lossValue: 530,
    duration: 'Minutes',
    category: 'cyber',
    tag: 'Cyber',
    short: 'One of the largest crypto exchange hacks in history — NEM tokens were drained from hot wallets.',
    story: [
      'In January 2018 attackers compromised Coincheck’s hot wallet holding NEM (XEM) tokens.',
      'Approximately $530 million worth of tokens were transferred out in a short period.',
      'The exchange lacked adequate cold-storage practices and multi-signature controls at the time.',
      'The incident accelerated industry adoption of cold storage, multi-sig, and insurance practices.',
    ],
    lessons: [
      'The vast majority of customer crypto should remain in cold storage.',
      'Multi-signature and hardware security modules are baseline requirements.',
      'Hot-wallet balances must be strictly limited and continuously monitored.',
    ],
    references: [
      { label: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Coincheck' },
    ],
  },
  {
    id: 'visa',
    title: 'Visa Outage',
    year: 2018,
    loss: 'Systemic',
    lossValue: 0,
    duration: '~10 hours',
    category: 'infrastructure',
    tag: 'Infrastructure',
    short: 'A partial failure in a data center caused widespread card payment disruptions across Europe.',
    story: [
      'On June 1, 2018 a hardware failure in a Visa data center cascaded into a major service disruption.',
      'Millions of card transactions across Europe failed or were delayed for most of a day.',
      'The incident highlighted single points of failure even in highly redundant global payment networks.',
      'It reinforced the need for active-active architectures and rigorous failover testing.',
    ],
    lessons: [
      'Critical payment infrastructure requires true geographic and system diversity.',
      'Failover procedures must be regularly tested under realistic load.',
      'Clear customer and merchant communication during outages is essential.',
    ],
    references: [],
  },
];

export const timeline = [
  { year: 2008, label: 'Madoff', id: 'madoff' },
  { year: 2012, label: 'Knight Capital', id: 'knight' },
  { year: 2016, label: 'Bangladesh', id: 'bangladesh' },
  { year: 2018, label: 'Coincheck / Visa', id: 'coincheck' },
  { year: 2020, label: 'Wirecard', id: 'wirecard' },
  { year: 2022, label: 'FTX', id: 'ftx' },
  { year: 2023, label: 'SVB', id: 'svb' },
];
